#!/bin/bash

for (( i=1; i<=$1; i++ )); do
        echo "Hello"
done
elizaveta@elizaveta-VirtualBox:~$ ./myscript.sh 15
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
#!/bin/bash

sum=$(($1+$2))

echo "$sum"
elizaveta@elizaveta-VirtualBox:~$ ./add.sh 146 5
151
  GNU nano 4.8                         op2.sh                                   
#!/bin/bash

if [ "$3" == "add" ] || [ "$3" == "sub" ] || [ "$3" == "mul" ] 
then
case $3 in
"add") echo $[$1+$2] ;;
"sub") echo $[$1-$2] ;;
"mul") echo $[$1*$2] ;;
esac
else
case $ARITHMETIC_OP in
"add") echo $[$1+$2] ;;
"sub") echo $[$1-$2] ;;
"mul") echo $[$1*$2] ;;
*) echo "wrong ARITHMETIC_OP" ;;
esac
fi
elizaveta@elizaveta-VirtualBox:~$ ./op2.sh 17 8 sub
9
elizaveta@elizaveta-VirtualBox:~$ export ARITHMETIC_OP=mul
elizaveta@elizaveta-VirtualBox:~$ ./op2.sh 17 8 
136
